/**
 * Simulation State & Reducers for ChaosToClarityExperience
 * 
 * 100% In-Memory State Machine. Zero external database mutations.
 */

import {
  ChaosToClarityState,
  IndustryKey,
  IndustryConfig,
  StoryStep,
  StoryStepNumber,
  HotspotId,
  HotspotInfo,
} from "../types";

export const INDUSTRY_CONFIGS: Record<IndustryKey, IndustryConfig> = {
  clinic: {
    id: "clinic",
    label: "🏥 Healthcare Clinic & OPD",
    icon: "🏥",
    locationName: "Metro Care Clinic & Consultation",
    customerTitle: "Patient",
    staffTitle: "Receptionist",
    counterTitle: "Front Desk & Triage",
    serviceAction: "Consultation Call",
    beforeChaosDescription: "Crowded waiting lounge with 15 anxious patients repeatedly asking the receptionist how long until their doctor's appointment.",
    afterClarityDescription: "Patients join via QR code, relax at nearby coffee shops or work quietly, and arrive 5 minutes before their consultation room is ready.",
    defaultWaitEstimate: "~35 to 45 mins (uncertain)",
    protagonistName: "Dr. Kavita / Patient Anya",
    protagonistRole: "Product Designer with 2PM Client Call",
    opportunityCostNote: "Has an urgent client pitch in 45 minutes; unable to sit in crowded room without knowing actual turn time.",
  },
  restaurant: {
    id: "restaurant",
    label: "☕ Dining & Cafe",
    icon: "☕",
    locationName: "Artisan Kitchen & Grill",
    customerTitle: "Dining Guest",
    staffTitle: "Host / Captain",
    counterTitle: "Host Stand",
    serviceAction: "Table Readiness Alert",
    beforeChaosDescription: "Hungry diners clustering in the doorway, blocking walkways while the host scribbles paper names and answers repeated table status inquiries.",
    afterClarityDescription: "Guests scan QR standee, browse nearby boutiques, and receive a table ready buzz on their phone 2 minutes prior.",
    defaultWaitEstimate: "~25 to 40 mins",
    protagonistName: "Guest Rahul & Friends",
    protagonistRole: "Party of 4 celebrating birthday",
    opportunityCostNote: "Waiting outside in heat; debating walking away to another restaurant across the street.",
  },
  salon: {
    id: "salon",
    label: "💇 Salon & Spa",
    icon: "💇",
    locationName: "Luxe Studio & Styling Lounge",
    customerTitle: "Salon Client",
    staffTitle: "Front Desk Stylist",
    counterTitle: "Styling Reception",
    serviceAction: "Stylist Station Call",
    beforeChaosDescription: "Walk-in clients sitting shoulder-to-shoulder with wet hair and magazines, unaware if their stylist is delayed on a previous treatment.",
    afterClarityDescription: "Live rolling wait time updates let clients run errands or grab lunch without risking losing their styling chair slot.",
    defaultWaitEstimate: "~20 to 30 mins",
    protagonistName: "Client Priya",
    protagonistRole: "Executive getting haircut between meetings",
    opportunityCostNote: "Stuck in salon lobby unable to take confidential calls while waiting for a free chair.",
  },
  government: {
    id: "government",
    label: "🏛️ Citizen Service Counter",
    icon: "🏛️",
    locationName: "Municipal Citizen Civic Center",
    customerTitle: "Citizen Applicant",
    staffTitle: "Desk Officer",
    counterTitle: "Permit Counter #4",
    serviceAction: "Token Number Call",
    beforeChaosDescription: "Hundreds of citizens clutching crumpled paper tokens, crowding around a single flickering LED board with zero progress estimates.",
    afterClarityDescription: "Citizens track their exact position from their mobile browser, leaving the stuffy hall and arriving precisely when their token is called.",
    defaultWaitEstimate: "~60 to 90 mins",
    protagonistName: "Citizen Deepak",
    protagonistRole: "Renewing vehicle registration",
    opportunityCostNote: "Took half-day off work; stressed about returning to office on time.",
  },
  diagnostic: {
    id: "diagnostic",
    label: "🔬 Diagnostic & Blood Lab",
    icon: "🔬",
    locationName: "Precision Pathology & Scan Lab",
    customerTitle: "Fasting Patient",
    staffTitle: "Lab Receptionist",
    counterTitle: "Sample Collection Desk",
    serviceAction: "Phlebotomy Call",
    beforeChaosDescription: "Fasting patients standing since 7:30 AM, hungry and irritable, repeatedly asking when their blood draw token will be called.",
    afterClarityDescription: "Precise queue visibility lets fasting patients wait in their car or shaded garden until 2 minutes before their collection booth opens.",
    defaultWaitEstimate: "~30 mins",
    protagonistName: "Patient Meera",
    protagonistRole: "Fasting for diabetic test panel",
    opportunityCostNote: "Fasting since last night; feeling dizzy in the crowded waiting room.",
  },
};

export const STORY_STEPS: StoryStep[] = [
  {
    number: 1,
    id: "the_problem",
    tagline: "01 • Physical Uncertainty",
    title: "The Overwhelmed Waiting Room",
    beforeDescription: "A busy waiting room packed with people. Customers sit anxiously checking their watches, with zero idea how many people are actually ahead of them.",
    afterDescription: "The physical lobby is calm and spacious. 80% of patients wait comfortably outside, knowing their exact digital position.",
    humanContext: "Anya arrives at 1:15 PM with an urgent 2:00 PM team pitch. Physical waiting leaves her completely blind on whether she'll make it in time.",
    hotspotTarget: "waiting_lounge",
    presenterCue: "Notice the crowded seating and body language of uncertainty.",
  },
  {
    number: 2,
    id: "the_friction",
    tagline: "02 • Repeated Interruptions",
    title: "The Receptionist Dilemma",
    beforeDescription: "The front desk receptionist is interrupted every 90 seconds with the same question: 'How much longer until my turn?' She has to guess: 'Maybe 30-40 minutes...'",
    afterDescription: "Receptionist works with uninterrupted focus. A live staff counter terminal handles all customer routing digitally.",
    humanContext: "Front desk staff spend 60% of their day answering repetitive wait inquiries instead of handling care registration.",
    hotspotTarget: "reception",
    presenterCue: "Observe the constant interruptions at the counter desk.",
  },
  {
    number: 3,
    id: "the_scan",
    tagline: "03 • Zero-App QR Discovery",
    title: "The 3-Second Scan Moment",
    beforeDescription: "Anya spots a paper clipboard or static sign with no live updates. Frustration builds as time ticks away.",
    afterDescription: "Anya spots the prominent Qblink Standee: 'Scan to Join & Wait Anywhere'. She opens her camera without installing any app.",
    humanContext: "Zero app download barrier. Works instantly on iOS Safari or Android Chrome via standard web URL.",
    hotspotTarget: "qr_standee",
    presenterCue: "Show the simulated camera scan over the QR standee.",
  },
  {
    number: 4,
    id: "the_join",
    tagline: "04 • Instant Live Pass",
    title: "Digital Token Issued in Browser",
    beforeDescription: "Paper tokens get crumpled or lost. When your number is called verbally, if you stepped out for fresh air, you forfeit your turn.",
    afterDescription: "Browser instantly generates Token #A-27: '3 people ahead • ~9 min estimated wait • Moving normally'.",
    humanContext: "Anya now has total transparency. She knows she has 9 minutes of free time.",
    hotspotTarget: "protagonist",
    presenterCue: "Highlight the customer's phone showing token #A-27 and real-time wait estimation.",
  },
  {
    number: 5,
    id: "remote_waiting",
    tagline: "05 • Freedom to Move",
    title: "Waiting Outside the Crowded Room",
    beforeDescription: "Patients are held hostage in a high-risk crowded room for 45 minutes just to keep their spot in line.",
    afterDescription: "Anya walks to the open-air coffee terrace across the street, opens her laptop, and finishes her presentation slides in peace.",
    humanContext: "Waiting is transformed from lost dead time into productive personal time.",
    hotspotTarget: "remote_cafe",
    presenterCue: "Demonstrate remote waiting in a relaxed environment.",
  },
  {
    number: 6,
    id: "turn_alert",
    tagline: "06 • Turn-Approaching Alert",
    title: "Dynamic Alert & Arrival Grace",
    beforeDescription: "Doctor calls the next patient. If absent, staff waste 5 minutes shouting in the lobby or skip them.",
    afterDescription: "Phone drops a vibration alert: 'You're Next in Line! Please head toward Consultation Room 3.' Anya walks in calmly.",
    humanContext: "The 'I'm 2 Mins Away' grace hold eliminates missed turns and keeps doctors on schedule.",
    hotspotTarget: "queue_display",
    presenterCue: "Show the turn alert and graceful counter arrival.",
  },
  {
    number: 7,
    id: "calm_flow",
    tagline: "07 • The Complete Transformation",
    title: "From Chaos to Controlled Flow",
    beforeDescription: "Physical crowding, frayed tempers, high walkaway rates, and stressed staff.",
    afterDescription: "Seamless synchronized flow. Patients know when to arrive; businesses have predictable schedules.",
    humanContext: "Both sides win: The patient gets their time back, and the clinic operates at peak calm velocity.",
    hotspotTarget: "staff_terminal",
    presenterCue: "Conclude the story: Physical uncertainty replaced by digital visibility.",
  },
];

export const HOTSPOTS: HotspotInfo[] = [
  {
    id: "reception",
    label: "Front Desk & Reception",
    category: "problem",
    beforeNote: "Staff repeatedly interrupted by anxious patients asking for wait estimates.",
    afterNote: "Staff operates calmly with a digital terminal showing live queue progress.",
    x: 28,
    y: 42,
  },
  {
    id: "waiting_lounge",
    label: "Main Waiting Lounge",
    category: "problem",
    beforeNote: "Crowded room with 15 patients sitting and standing with high anxiety.",
    afterNote: "Spacious, airy room; 80% of patients wait remotely and arrive just in time.",
    x: 62,
    y: 56,
  },
  {
    id: "qr_standee",
    label: "Qblink QR Standee",
    category: "solution",
    beforeNote: "Static paper notices or clipboards providing zero live visibility.",
    afterNote: "Scan to join in 3 seconds directly in browser. No app download required.",
    x: 42,
    y: 68,
  },
  {
    id: "protagonist",
    label: "Patient Anya (Protagonist)",
    category: "problem",
    beforeNote: "Anxious, checking watch, stressed about her 2PM client pitch.",
    afterNote: "Holding live digital pass on phone; relaxed and in total control.",
    x: 48,
    y: 48,
  },
  {
    id: "queue_display",
    label: "Digital Token Display",
    category: "solution",
    beforeNote: "Flickering or absent token display; verbal shouting of names.",
    afterNote: "Crisp live display showing current tokens and QR scan prompt.",
    x: 75,
    y: 28,
  },
  {
    id: "staff_terminal",
    label: "Staff Control Terminal",
    category: "device",
    beforeNote: "Paper logbooks and manual guesswork for queue order.",
    afterNote: "Real-time dispatch console with 1-click 'Call Next' and velocity metrics.",
    x: 22,
    y: 36,
  },
  {
    id: "wall_clock",
    label: "Elapsed Time Clock",
    category: "problem",
    beforeNote: "45 minutes of dead waiting time lost in physical uncertainty.",
    afterNote: "Time reclaimed: patient works or relaxes comfortably nearby.",
    x: 50,
    y: 18,
  },
  {
    id: "remote_cafe",
    label: "Nearby Waiting Zone (Cafe)",
    category: "solution",
    beforeNote: "Patients unable to leave the room for fear of losing their place in line.",
    afterNote: "Patients wait anywhere within 5 minutes radius with peace of mind.",
    x: 88,
    y: 45,
  },
];

export function createInitialSimulationState(industry: IndustryKey = "clinic"): ChaosToClarityState {
  return {
    industry,
    phase: "before",
    storyStep: 1,
    mode: "guided",
    activeHotspot: null,
    perspective: "scene",
    fastForwardMinutes: 0,
    isMuted: true,
    isPlayingTour: false,
    cameraAngle: 0,
  };
}
