import { useState, useMemo } from "react";
import {
  BarChart3,
  Clock,
  Users,
  CheckCircle2,
  AlertTriangle,
  TrendingUp,
  Share2,
  Printer,
  X,
  Sparkles,
  Zap,
} from "lucide-react";
import {
  computeDailyPerformanceSummary,
  DailyPerformanceReport,
  VisitorHistoryRecord,
} from "@/lib/dailySummaryCalculator";
import { toast } from "sonner";
import { hapticCopy, hapticSuccess } from "@/lib/haptics";

interface Props {
  businessId: string;
  businessName: string;
  visitors: VisitorHistoryRecord[];
  onClose: () => void;
}

export const DailyPerformanceSummary = ({
  businessId,
  businessName,
  visitors,
  onClose,
}: Props) => {
  const summary: DailyPerformanceReport = useMemo(() => {
    return computeDailyPerformanceSummary({
      businessId,
      businessName,
      visitors,
    });
  }, [businessId, businessName, visitors]);

  const handleShareSummary = () => {
    const text = `📊 Daily Flow Summary for ${businessName} (${summary.date})\n` +
      `• Total Served: ${summary.totalServed.value} customers\n` +
      `• Avg Wait Time: ${summary.avgWaitMinutes.hasData ? `${summary.avgWaitMinutes.value} mins` : "N/A"}\n` +
      `• Avg Service Speed: ${summary.avgServiceMinutes.hasData ? `${summary.avgServiceMinutes.value} min/person` : "N/A"}\n` +
      `• Flow Health Score: ${summary.flowEfficiencyScore.value}/100\n` +
      `• Peak Window: ${summary.peakHour.value || "Even distribution"}\n` +
      `Generated by Qblink Flow Intelligence`;

    navigator.clipboard.writeText(text);
    hapticCopy();
    toast.success("Daily summary copied to clipboard!");
  };

  const handlePrint = () => {
    hapticSuccess();
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-background/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="bg-card border border-border rounded-3xl max-w-3xl w-full max-h-[90vh] overflow-y-auto card-shadow flex flex-col">
        {/* Header */}
        <div className="p-6 border-b border-border flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-primary/10 flex items-center justify-center text-primary font-bold">
              <BarChart3 className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-foreground">Daily Operations Summary</h2>
              <p className="text-xs text-muted-foreground">
                {businessName} • {summary.date} • Real-world Flow Metrics
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl text-muted-foreground hover:text-foreground hover:bg-muted/50 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 space-y-6">
          {/* Key Metric Grid */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            {/* Total Served */}
            <div className="p-4 rounded-2xl bg-muted/40 border border-border flex flex-col justify-between">
              <div className="flex items-center justify-between text-muted-foreground text-xs font-semibold uppercase">
                <span>Served</span>
                <CheckCircle2 className="w-4 h-4 text-success" />
              </div>
              <div className="mt-3">
                <span className="text-3xl font-black text-foreground">{summary.totalServed.value}</span>
                <span className="text-xs text-muted-foreground ml-1.5">/ {summary.totalJoined.value} joined</span>
              </div>
            </div>

            {/* Average Wait */}
            <div className="p-4 rounded-2xl bg-muted/40 border border-border flex flex-col justify-between">
              <div className="flex items-center justify-between text-muted-foreground text-xs font-semibold uppercase">
                <span>Avg Wait</span>
                <Clock className="w-4 h-4 text-primary" />
              </div>
              <div className="mt-3">
                <span className="text-3xl font-black text-foreground">
                  {summary.avgWaitMinutes.hasData ? summary.avgWaitMinutes.value : "—"}
                </span>
                <span className="text-xs text-muted-foreground ml-1.5">min</span>
              </div>
            </div>

            {/* Average Service Duration */}
            <div className="p-4 rounded-2xl bg-muted/40 border border-border flex flex-col justify-between">
              <div className="flex items-center justify-between text-muted-foreground text-xs font-semibold uppercase">
                <span>Service Velocity</span>
                <Zap className="w-4 h-4 text-amber-500" />
              </div>
              <div className="mt-3">
                <span className="text-3xl font-black text-foreground">
                  {summary.avgServiceMinutes.hasData ? summary.avgServiceMinutes.value : "—"}
                </span>
                <span className="text-xs text-muted-foreground ml-1.5">min/ticket</span>
              </div>
            </div>

            {/* Flow Health Score */}
            <div className="p-4 rounded-2xl bg-muted/40 border border-border flex flex-col justify-between">
              <div className="flex items-center justify-between text-muted-foreground text-xs font-semibold uppercase">
                <span>Flow Score</span>
                <TrendingUp className="w-4 h-4 text-emerald-500" />
              </div>
              <div className="mt-3">
                <span className="text-3xl font-black text-emerald-500">{summary.flowEfficiencyScore.value}</span>
                <span className="text-xs text-muted-foreground ml-1.5">/ 100</span>
              </div>
            </div>
          </div>

          {/* Peak Hour Banner */}
          <div className="p-4 rounded-2xl bg-primary/5 border border-primary/20 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <span className="text-2xl">⚡</span>
              <div>
                <h4 className="text-sm font-bold text-foreground">
                  {summary.peakHour.hasData ? `Peak Traffic Window: ${summary.peakHour.value}` : "Steady Flow Throughout the Day"}
                </h4>
                <p className="text-xs text-muted-foreground">
                  {summary.peakHour.hasData
                    ? `Highest traffic period with ${summary.peakHourCount} customers checking in.`
                    : "No concentrated bottleneck recorded today."}
                </p>
              </div>
            </div>
            <span className="text-xs font-bold text-primary px-3 py-1 bg-primary/10 rounded-full">
              {summary.noShowRatePct.value}% No-Show
            </span>
          </div>

          {/* Hourly Traffic Bar Chart */}
          <div className="p-5 rounded-2xl bg-muted/30 border border-border">
            <h4 className="text-xs font-bold text-foreground uppercase tracking-wider mb-4 flex items-center justify-between">
              <span>Hourly Customer Volume Distribution</span>
              <span className="text-[11px] font-normal text-muted-foreground">8:00 AM – 9:00 PM</span>
            </h4>
            <div className="grid grid-cols-7 sm:grid-cols-14 gap-1.5 items-end h-28 pt-2">
              {summary.hourlyDistribution.map((slot) => {
                const maxInDay = Math.max(...summary.hourlyDistribution.map((d) => d.count), 1);
                const heightPct = Math.max(8, (slot.count / maxInDay) * 100);
                const isPeak = slot.count === maxInDay && slot.count > 0;
                return (
                  <div key={slot.hour} className="flex flex-col items-center gap-1.5 group h-full justify-end">
                    <div
                      style={{ height: `${heightPct}%` }}
                      className={`w-full rounded-lg transition-all duration-300 ${
                        isPeak ? "bg-primary shadow-sm" : slot.count > 0 ? "bg-primary/50" : "bg-muted/80"
                      }`}
                      title={`${slot.label}: ${slot.count} customers`}
                    />
                    <span className="text-[9px] font-mono text-muted-foreground group-hover:text-foreground">
                      {slot.hour % 12 === 0 ? 12 : slot.hour % 12}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="p-6 border-t border-border bg-muted/20 flex items-center justify-between">
          <span className="text-xs text-muted-foreground">
            Data computed directly from verified queue events. Zero synthetic inflation.
          </span>
          <div className="flex items-center gap-2">
            <button
              onClick={handleShareSummary}
              className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl border border-border bg-card text-xs font-semibold text-foreground hover:bg-muted/50 transition-colors"
            >
              <Share2 className="w-3.5 h-3.5" />
              Share Summary
            </button>
            <button
              onClick={handlePrint}
              className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-primary text-primary-foreground text-xs font-semibold hover:opacity-90 transition-all shadow-md"
            >
              <Printer className="w-3.5 h-3.5" />
              Print Report
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
