CREATE TABLE IF NOT EXISTS public.queue_live_signals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  queue_id UUID NOT NULL,
  event_type TEXT NOT NULL DEFAULT 'queue_changed',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT ON public.queue_live_signals TO anon, authenticated;
GRANT ALL ON public.queue_live_signals TO service_role;

ALTER TABLE public.queue_live_signals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read queue live signals" ON public.queue_live_signals;
CREATE POLICY "Anyone can read queue live signals"
ON public.queue_live_signals
FOR SELECT
USING (true);

CREATE OR REPLACE FUNCTION public.emit_queue_live_signal()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_queue_id uuid;
  v_event text;
BEGIN
  IF TG_TABLE_NAME = 'queues' THEN
    v_queue_id := COALESCE(NEW.id, OLD.id);
    v_event := 'queue_' || lower(TG_OP);
  ELSE
    v_queue_id := COALESCE(NEW.queue_id, OLD.queue_id);
    v_event := 'visitor_' || lower(TG_OP);
  END IF;

  IF v_queue_id IS NOT NULL THEN
    INSERT INTO public.queue_live_signals (queue_id, event_type)
    VALUES (v_queue_id, v_event);
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS queue_live_signal_on_queues ON public.queues;
CREATE TRIGGER queue_live_signal_on_queues
AFTER INSERT OR UPDATE OR DELETE ON public.queues
FOR EACH ROW EXECUTE FUNCTION public.emit_queue_live_signal();

DROP TRIGGER IF EXISTS queue_live_signal_on_visitors ON public.queue_visitors;
CREATE TRIGGER queue_live_signal_on_visitors
AFTER INSERT OR UPDATE OR DELETE ON public.queue_visitors
FOR EACH ROW EXECUTE FUNCTION public.emit_queue_live_signal();

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.queue_live_signals;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;